In [2]:
import pandas as pd

In [3]:
df_people = pd.read_csv('C:/Users/human/미정프로젝트/서울시 상권분석서비스(길단위인구-상권).csv',
                        encoding='cp949')

df_area = pd.read_csv('C:/Users/human/미정프로젝트/서울시 상권분석서비스(영역-상권).csv',
                      encoding='cp949')

df_sales = pd.read_csv('C:/Users/human/미정프로젝트/서울시 상권분석서비스(추정매출-상권).csv',
                       encoding='cp949')

print(f'길단위인구: {len(df_people):,}행')
print(f'영역: {len(df_area):,}행')
print(f'추정매출: {len(df_sales):,}행')

길단위인구: 46,184행
영역: 1,650행
추정매출: 85,732행

In [4]:
print('=== 길단위인구 컬럼 ===')
print(df_people.columns.tolist())
print()
print('=== 영역 컬럼 ===')
print(df_area.columns.tolist())
print()
print('=== 추정매출 컬럼 ===')
print(df_sales.columns.tolist())

=== 길단위인구 컬럼 ===
['기준_년분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '총_유동인구_수', '남성_유동인구_수', '여성_유동인구_수', '연령대_10_유동인구_수', '연령대_20_유동인구_수', '연령대_30_유동인구_수', '연령대_40_유동인구_수', '연령대_50_유동인구_수', '연령대_60_이상_유동인구_수', '시간대_00_06_유동인구_수', '시간대_06_11_유동인구_수', '시간대_11_14_유동인구_수', '시간대_14_17_유동인구_수', '시간대_17_21_유동인구_수', '시간대_21_24_유동인구_수', '월요일_유동인구_수', '화요일_유동인구_수', '수요일_유동인구_수', '목요일_유동인구_수', '금요일_유동인구_수', '토요일_유동인구_수', '일요일_유동인구_수']

=== 영역 컬럼 ===
['상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '엑스좌표_값', '와이좌표_값', '자치구_코드', '자치구_코드_명', '행정동_코드', '행정동_코드_명', '영역_면적']

=== 추정매출 컬럼 ===
['기준_년분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '당월_매출_금액', '당월_매출_건수', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액', '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액', '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액', '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액', '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수', '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수', '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수', '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수', '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수', '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수', '연령대_50_매출_건수', '연령대_60_이상_매출_건수']

In [5]:
# 영역에서 필요한 컬럼만 추출
df_area_slim = df_area[['상권_코드', '상권_코드_명', '자치구_코드_명', '행정동_코드_명', '영역_면적']]

# 길단위인구 + 영역 합치기
df_merged = pd.merge(df_people, df_area_slim, on='상권_코드', how='left')

print(f'합치기 전: {len(df_people):,}행')
print(f'합치기 후: {len(df_merged):,}행')
print()
print(df_merged[['상권_코드', '자치구_코드_명', '총_유동인구_수', '연령대_20_유동인구_수']].head())

합치기 전: 46,184행
합치기 후: 46,184행

     상권_코드 자치구_코드_명  총_유동인구_수  연령대_20_유동인구_수
0  3001496      강남구    109921          21760
1  3001495      송파구   4226024         974324
2  3001494      종로구   8405499        1499669
3  3001493       중구   3312549         617894
4  3001492       중구   7288146        1248220

In [6]:
# 추정매출 상권별 평균으로 집계
df_sales_agg = df_sales.groupby('상권_코드').agg(
    평균_당월매출=('당월_매출_금액', 'mean'),
    평균_주중매출=('주중_매출_금액', 'mean'),
    평균_주말매출=('주말_매출_금액', 'mean'),
    연령대_20_매출=('연령대_20_매출_금액', 'mean'),
    연령대_30_매출=('연령대_30_매출_금액', 'mean'),
    연령대_40_매출=('연령대_40_매출_금액', 'mean'),
    연령대_50_매출=('연령대_50_매출_금액', 'mean'),
).reset_index()

# 합치기
df_merged = pd.merge(df_merged, df_sales_agg, on='상권_코드', how='left')

print(f'합치기 후: {len(df_merged):,}행')
print(f'컬럼 수: {len(df_merged.columns)}개')
df_merged.head(3)

합치기 후: 46,184행
컬럼 수: 38개

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명_x,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,자치구_코드_명,행정동_코드_명,영역_면적,평균_당월매출,평균_주중매출,평균_주말매출,연령대_20_매출,연령대_30_매출,연령대_40_매출,연령대_50_매출
0,20254,U,관광특구,3001496,강남 마이스 관광특구,109921,53290,56631,8894,21760,...,강남구,삼성1동,237892,3.409830e+09,2.328020e+09,1.081810e+09,4.241326e+08,8.349584e+08,7.428475e+08,5.173117e+08
1,20254,U,관광특구,3001495,잠실 관광특구,4226024,1994837,2231189,443601,974324,...,송파구,방이2동,2462734,9.303798e+09,5.877776e+09,3.426021e+09,1.604722e+09,2.798510e+09,2.014408e+09,1.429009e+09
2,20254,U,관광특구,3001494,종로?청계 관광특구,8405499,4432125,3973375,353225,1499669,...,종로구,종로1?2?3?4가동,653127,4.552223e+09,3.574068e+09,9.781544e+08,3.459151e+08,7.562753e+08,6.560959e+08,8.773900e+08

In [7]:
# 핵심 컬럼만 선택
df_final = df_merged[[
    '자치구_코드_명',
    '총_유동인구_수',
    '연령대_20_유동인구_수',
    '연령대_30_유동인구_수',
    '연령대_40_유동인구_수',
    '연령대_50_유동인구_수',
    '연령대_60_이상_유동인구_수',
    '시간대_11_14_유동인구_수',
    '시간대_17_21_유동인구_수',
    '평균_당월매출',
    '평균_주중매출',
    '평균_주말매출',
    '연령대_20_매출',
    '연령대_30_매출',
    '연령대_40_매출',
    '연령대_50_매출',
    '영역_면적'
]].copy()

# 구별 평균으로 집계
df_gu = df_final.groupby('자치구_코드_명').mean().reset_index()
df_gu = df_gu.rename(columns={'자치구_코드_명': '구명'})

print(f'행 수: {len(df_gu)}개 (25개 구)')
df_gu.head()

행 수: 25개 (25개 구)

,구명,총_유동인구_수,연령대_20_유동인구_수,연령대_30_유동인구_수,연령대_40_유동인구_수,연령대_50_유동인구_수,연령대_60_이상_유동인구_수,시간대_11_14_유동인구_수,시간대_17_21_유동인구_수,평균_당월매출,평균_주중매출,평균_주말매출,연령대_20_매출,연령대_30_매출,연령대_40_매출,연령대_50_매출,영역_면적
0,강남구,8.950147e+05,167135.604304,207987.137452,177369.223186,113067.774384,123006.340507,146559.491843,165059.657411,1.025076e+09,8.038951e+08,2.211808e+08,8.418348e+07,1.908548e+08,2.517847e+08,1.859152e+08,122947.482471
1,강동구,1.150884e+06,144041.559524,180750.268452,183971.296429,178479.799405,285467.065476,133067.948810,188986.794048,4.831679e+08,3.653507e+08,1.178172e+08,2.678737e+07,7.095443e+07,1.138678e+08,1.057534e+08,96016.850000
2,강북구,8.822578e+05,133038.028912,115591.619048,130240.126417,143402.057256,246711.299320,102035.906463,147034.138322,3.369267e+08,2.408909e+08,9.603578e+07,2.152070e+07,4.724257e+07,6.114621e+07,8.280136e+07,75212.047619
3,강서구,8.966089e+05,129296.309184,161370.632653,143482.645408,123361.019388,201562.544898,103148.110714,147605.521939,7.131045e+08,5.292928e+08,1.838117e+08,3.600863e+07,9.946540e+07,1.334652e+08,1.426491e+08,124092.271429
4,관악구,1.025460e+06,265986.974903,201341.359556,140990.554537,124056.362934,195016.582529,113029.568533,172631.670849,3.231949e+08,2.371409e+08,8.605406e+07,3.786214e+07,6.176193e+07,5.437149e+07,6.562325e+07,80629.567568

In [9]:
# 1번에서 저장한 폐업률 파일 불러오기
df_closure = pd.read_csv('C:/Users/human/미정프로젝트/폐업률_구별_최근5년.csv', encoding='utf-8-sig')

# 구명 기준으로 합치기
df_ml = pd.merge(df_gu, df_closure[['구명', '폐업률']], on='구명', how='left')

print(f'결측치 확인:')
print(df_ml['폐업률'].isnull().sum())
print()
print(df_ml[['구명', '총_유동인구_수', '평균_당월매출', '폐업률']].head(10))

결측치 확인:
0

    구명      총_유동인구_수       평균_당월매출    폐업률
0  강남구  8.950147e+05  1.025076e+09  53.33
1  강동구  1.150884e+06  4.831679e+08  48.75
2  강북구  8.822578e+05  3.369267e+08  46.91
3  강서구  8.966089e+05  7.131045e+08  48.03
4  관악구  1.025460e+06  3.231949e+08  47.64
5  광진구  9.671186e+05  4.077091e+08  43.95
6  구로구  7.620068e+05  4.651409e+08  47.94
7  금천구  5.600571e+05  1.652206e+09  38.69
8  노원구  8.592204e+05  4.837560e+08  47.88
9  도봉구  6.768697e+05  4.092920e+08  42.07

In [10]:
df_ml.to_csv('상권_폐업률_ML용.csv', index=False, encoding='utf-8-sig')

print('저장 완료!')
print(f'최종 데이터: {len(df_ml)}행 x {len(df_ml.columns)}컬럼')
print()
print('컬럼 목록:')
print(df_ml.columns.tolist())

저장 완료!
최종 데이터: 25행 x 18컬럼

컬럼 목록:
['구명', '총_유동인구_수', '연령대_20_유동인구_수', '연령대_30_유동인구_수', '연령대_40_유동인구_수', '연령대_50_유동인구_수', '연령대_60_이상_유동인구_수', '시간대_11_14_유동인구_수', '시간대_17_21_유동인구_수', '평균_당월매출', '평균_주중매출', '평균_주말매출', '연령대_20_매출', '연령대_30_매출', '연령대_40_매출', '연령대_50_매출', '영역_면적', '폐업률']

In [11]:
# 외식 업종만 필터링
food_list = ['한식음식점', '중식음식점', '일식음식점', '양식음식점',
             '분식전문점', '치킨전문점', '커피-음료', '패스트푸드점']

df_food = df_sales[df_sales['서비스_업종_코드_명'].isin(food_list)].copy()

print(f'전체 매출 데이터: {len(df_sales):,}행')
print(f'외식 업종만: {len(df_food):,}행')
print()
print(df_food[['상권_코드_명', '서비스_업종_코드_명', '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액']].head())

전체 매출 데이터: 85,732행
외식 업종만: 21,226행

        상권_코드_명 서비스_업종_코드_명  연령대_20_매출_금액  연령대_30_매출_금액  연령대_40_매출_금액
20  강남 마이스 관광특구       커피-음료    1022747083    2065183871    1487723456
21  강남 마이스 관광특구       분식전문점     265212382     379827838     328846300
22  강남 마이스 관광특구      패스트푸드점     291419039     453011746     351202643
24  강남 마이스 관광특구       양식음식점     850514338    2304929965    1960422450
25  강남 마이스 관광특구       일식음식점     105670770     164483305      81350339

In [12]:
# 영역 파일에서 구 이름 가져오기
df_food_area = pd.merge(df_food, df_area_slim, on='상권_코드', how='left')

# 구별 + 업종별 연령대 매출 평균
df_age_food = df_food_area.groupby(['자치구_코드_명', '서비스_업종_코드_명']).agg(
    매출_20대=('연령대_20_매출_금액', 'mean'),
    매출_30대=('연령대_30_매출_금액', 'mean'),
    매출_40대=('연령대_40_매출_금액', 'mean'),
    매출_50대=('연령대_50_매출_금액', 'mean'),
    매출_60대이상=('연령대_60_이상_매출_금액', 'mean'),
).reset_index()

df_age_food = df_age_food.rename(columns={'자치구_코드_명': '구명'})

print(df_age_food.head(10))
print(f'\n총 조합 수: {len(df_age_food)}개')

    구명 서비스_업종_코드_명        매출_20대        매출_30대        매출_40대        매출_50대  \
0  강남구       분식전문점  6.951462e+07  1.332296e+08  1.516277e+08  1.243822e+08
1  강남구       양식음식점  2.039243e+08  4.424446e+08  2.967830e+08  2.055420e+08
2  강남구       일식음식점  1.322360e+08  2.753102e+08  1.742960e+08  1.218776e+08
3  강남구       중식음식점  1.582224e+08  2.653530e+08  2.034503e+08  1.649156e+08
4  강남구       치킨전문점  2.523916e+07  5.842834e+07  6.241123e+07  5.677124e+07
5  강남구       커피-음료  1.983823e+08  3.636957e+08  2.444512e+08  1.672173e+08
6  강남구      패스트푸드점  5.980504e+07  1.030036e+08  9.632547e+07  7.224212e+07
7  강남구       한식음식점  4.168835e+08  1.014127e+09  8.468298e+08  7.213980e+08
8  강동구       분식전문점  4.594199e+07  8.245300e+07  1.482542e+08  1.081581e+08
9  강동구       양식음식점  9.818924e+07  1.465536e+08  1.205224e+08  1.060507e+08

       매출_60대이상
0  6.959905e+07
1  1.113459e+08
2  8.143652e+07
3  1.143749e+08
4  2.844839e+07
5  8.670557e+07
6  3.115281e+07
7  5.812557e+08
8  7.126808e+07
9  6.225866e+07

총 조합 수: 200개

In [13]:
df_age_food.to_csv('구별_업종별_연령대매출.csv', index=False, encoding='utf-8-sig')
print('저장 완료!')

저장 완료!

In [14]:
files = {
    2019: 'C:/Users/human/미정프로젝트/데이터 전처리/추정매출/서울시_상권분석서비스(추정매출-상권)_2019년.csv',
    2020: 'C:/Users/human/미정프로젝트/데이터 전처리/추정매출/서울시_상권분석서비스(추정매출-상권)_2020년.csv',
    2021: 'C:/Users/human/미정프로젝트/데이터 전처리/추정매출/서울시_상권분석서비스(추정매출-상권)_2021년.csv',
    2022: 'C:/Users/human/미정프로젝트/데이터 전처리/추정매출/서울시_상권분석서비스(추정매출-상권)_2022년.csv',
    2023: 'C:/Users/human/미정프로젝트/데이터 전처리/추정매출/서울시_상권분석서비스(추정매출-상권)_2023년.csv',
    2024: 'C:/Users/human/미정프로젝트/데이터 전처리/추정매출/서울시 상권분석서비스(추정매출-상권)_2024년.csv',
}

dfs = []
for year, path in files.items():
    df_temp = pd.read_csv(path, encoding='cp949')
    df_temp['연도'] = year
    dfs.append(df_temp)
    print(f'{year}년: {len(df_temp):,}행')

df_sales_all = pd.concat(dfs, ignore_index=True)
print(f'\n전체 합계: {len(df_sales_all):,}행')

2019년: 78,427행
2020년: 80,790행
2021년: 89,150행
2022년: 88,834행
2023년: 88,246행
2024년: 87,179행

전체 합계: 512,626행

In [20]:
# 외식 업종만 필터링
food_list = ['한식음식점', '중식음식점', '일식음식점', '양식음식점',
             '분식전문점', '치킨전문점', '커피-음료', '패스트푸드점']

df_food_all = df_sales_all[df_sales_all['서비스_업종_코드_명'].isin(food_list)].copy()

# 영역 파일에서 구 이름 붙이기
df_food_all = pd.merge(df_food_all, df_area_slim, on='상권_코드', how='left')

# 구 × 연도 × 업종별 매출 평균
df_sales_gu = df_food_all.groupby(['자치구_코드_명', '연도', '서비스_업종_코드_명']).agg(
    평균_당월매출=('당월_매출_금액', 'mean'),
    연령대_20_매출=('연령대_20_매출_금액', 'mean'),
    연령대_30_매출=('연령대_30_매출_금액', 'mean'),
    연령대_40_매출=('연령대_40_매출_금액', 'mean'),
    연령대_50_매출=('연령대_50_매출_금액', 'mean'),
).reset_index()

df_sales_gu = df_sales_gu.rename(columns={
    '자치구_코드_명': '구명',
    '서비스_업종_코드_명': '업종'
})

print(f'행 수: {len(df_sales_gu):,}개')
print(df_sales_gu.head())

행 수: 1,200개
    구명    연도     업종       평균_당월매출     연령대_20_매출     연령대_30_매출     연령대_40_매출  \
0  강남구  2019  분식전문점  6.533841e+08  1.279386e+08  1.448395e+08  1.427872e+08
1  강남구  2019  양식음식점  1.366631e+09  2.688714e+08  3.211270e+08  2.250849e+08
2  강남구  2019  일식음식점  9.675838e+08  1.774149e+08  2.076301e+08  1.397524e+08
3  강남구  2019  중식음식점  9.017192e+08  1.136016e+08  1.715209e+08  1.419383e+08
4  강남구  2019  치킨전문점  2.966859e+08  4.713372e+07  6.061216e+07  6.882087e+07

      연령대_50_매출
0  8.195965e+07
1  1.425676e+08
2  8.413404e+07
3  9.795975e+07
4  4.296152e+07

In [21]:
df_closure = pd.read_csv('C:/Users/human/미정프로젝트/새 폴더/폐업률_구별_연도별_업종별.csv', encoding='utf-8-sig')

# 구 + 연도 + 업종 기준으로 합치기
df_ml_final = pd.merge(df_sales_gu, df_closure[['구명', '연도', '업종', '폐업률']],
                       on=['구명', '연도', '업종'], how='left')

print(f'행 수: {len(df_ml_final):,}개')
print(f'결측치: {df_ml_final["폐업률"].isnull().sum()}개')
print(df_ml_final.head())

행 수: 1,200개
결측치: 163개
    구명    연도     업종       평균_당월매출     연령대_20_매출     연령대_30_매출     연령대_40_매출  \
0  강남구  2019  분식전문점  6.533841e+08  1.279386e+08  1.448395e+08  1.427872e+08
1  강남구  2019  양식음식점  1.366631e+09  2.688714e+08  3.211270e+08  2.250849e+08
2  강남구  2019  일식음식점  9.675838e+08  1.774149e+08  2.076301e+08  1.397524e+08
3  강남구  2019  중식음식점  9.017192e+08  1.136016e+08  1.715209e+08  1.419383e+08
4  강남구  2019  치킨전문점  2.966859e+08  4.713372e+07  6.061216e+07  6.882087e+07

      연령대_50_매출    폐업률
0  8.195965e+07  63.75
1  1.425676e+08  62.33
2  8.413404e+07  52.27
3  9.795975e+07  57.14
4  4.296152e+07  54.55

In [22]:
# 결측치 있는 행 확인
print('결측치 있는 조합:')
print(df_ml_final[df_ml_final['폐업률'].isnull()][['구명', '연도', '업종']].head(10))

# 결측치 제거
df_ml_final = df_ml_final.dropna(subset=['폐업률'])

print(f'\n결측치 제거 후: {len(df_ml_final):,}개')

결측치 있는 조합:
     구명    연도      업종
6   강남구  2019  패스트푸드점
14  강남구  2020  패스트푸드점
22  강남구  2021  패스트푸드점
30  강남구  2022  패스트푸드점
38  강남구  2023  패스트푸드점
46  강남구  2024  패스트푸드점
54  강동구  2019  패스트푸드점
62  강동구  2020  패스트푸드점
70  강동구  2021  패스트푸드점
78  강동구  2022  패스트푸드점

결측치 제거 후: 1,037개

In [23]:
# 결측치 구 평균으로 채우기
df_ml_final['폐업률'] = df_ml_final.groupby(['구명', '업종'])['폐업률'].transform(
    lambda x: x.fillna(x.mean())
)

print(f'결측치 남은 개수: {df_ml_final["폐업률"].isnull().sum()}')

결측치 남은 개수: 0

In [24]:
df_ml_final.to_csv('최종_ML용_데이터.csv', index=False, encoding='utf-8-sig')
print('저장 완료!')
print(f'최종 행 수: {len(df_ml_final):,}개')
print(f'컬럼: {df_ml_final.columns.tolist()}')

저장 완료!
최종 행 수: 1,037개
컬럼: ['구명', '연도', '업종', '평균_당월매출', '연령대_20_매출', '연령대_30_매출', '연령대_40_매출', '연령대_50_매출', '폐업률']

In [25]:
# 연도 추출 
df_people['연도'] = df_people['기준_년분기_코드'].astype(str).str[:4].astype(int)

# 구 이름 붙이기
df_people_area = pd.merge(df_people, df_area_slim, on='상권_코드', how='left')

# 구 × 연도별 유동인구 평균
df_people_gu = df_people_area.groupby(['자치구_코드_명', '연도']).agg(
    총_유동인구=('총_유동인구_수', 'mean'),
    유동인구_20대=('연령대_20_유동인구_수', 'mean'),
    유동인구_30대=('연령대_30_유동인구_수', 'mean'),
    유동인구_40대=('연령대_40_유동인구_수', 'mean'),
    유동인구_50대=('연령대_50_유동인구_수', 'mean'),
).reset_index()

df_people_gu = df_people_gu.rename(columns={'자치구_코드_명': '구명'})

# 2019~2024년만
df_people_gu = df_people_gu[df_people_gu['연도'] <= 2024]

print(f'행 수: {len(df_people_gu):,}개')
print(df_people_gu.head())

행 수: 150개
    구명    연도         총_유동인구       유동인구_20대       유동인구_30대       유동인구_40대  \
0  강남구  2019  928198.929612  184485.371359  219326.475728  170824.635922
1  강남구  2020  916064.050971  178571.655340  215503.689320  175009.487864
2  강남구  2021  871905.388350  163603.487864  204539.686893  171517.216019
3  강남구  2022  893557.631068  168685.764563  209469.618932  177922.825243
4  강남구  2023  897189.359223  165887.339806  208917.169903  181297.766990

        유동인구_50대
0  109888.747573
1  110989.199029
2  108914.728155
3  112186.817961
4  114841.788835

In [26]:
# 구 + 연도 기준으로 합치기
df_ml_final = pd.merge(df_ml_final, df_people_gu, on=['구명', '연도'], how='left')

print(f'행 수: {len(df_ml_final):,}개')
print(f'결측치: {df_ml_final.isnull().sum().sum()}개')
print(df_ml_final.columns.tolist())

행 수: 1,037개
결측치: 0개
['구명', '연도', '업종', '평균_당월매출', '연령대_20_매출', '연령대_30_매출', '연령대_40_매출', '연령대_50_매출', '폐업률', '총_유동인구', '유동인구_20대', '유동인구_30대', '유동인구_40대', '유동인구_50대']

In [27]:
print(f'df_ml_final 행 수: {len(df_ml_final):,}')
print(f'df_people_gu 연도 범위: {df_people_gu["연도"].unique()}')
print(f'df_ml_final 연도 범위: {df_ml_final["연도"].unique()}')

df_ml_final 행 수: 1,037
df_people_gu 연도 범위: [2019 2020 2021 2022 2023 2024]
df_ml_final 연도 범위: [2019 2020 2021 2022 2023 2024]

In [28]:
print(f'결측치 채우기 전 저장한 행 수 확인')
df_check = pd.read_csv('최종_ML용_데이터.csv', encoding='utf-8-sig')
print(f'저장된 파일 행 수: {len(df_check):,}')

결측치 채우기 전 저장한 행 수 확인
저장된 파일 행 수: 1,037

In [ ]:
# 패스트푸드 제외
df_ml_final = df_ml_final[df_ml_final['업종'] != '패스트푸드점'].copy()

print(f'제거 후 행 수: {len(df_ml_final):,}개')
print(f'남은 업종: {df_ml_final["업종"].unique()}')

df_ml_final.to_csv('최종_ML용_데이터.csv', index=False, encoding='utf-8-sig')
print('저장 완료!')

In [29]:
df_subway2 = pd.read_csv('C:/Users/human/미정프로젝트/서울_상권분석_용_정제_결측치처리_최종_데이터.csv',
                         encoding = 'utf-8-sig')
print(f'행 수: {len(df_subway2):,}개')
print(df_subway2[['사용월', '지하철역', '자치구']].head())

행 수: 50,274개
      사용월 지하철역   자치구
0  202604  동대문   종로구
1  202604  동묘앞   종로구
2  202604  서울역    중구
3  202604   시청    중구
4  202604  신설동  동대문구

In [30]:
#연도 추출
df_subway2['연도'] = df_subway2['사용월'].astype(str).str[:4].astype(int)
df_subway2 = df_subway2[(df_subway2['연도'] >= 2019) & (df_subway2['연도'] <= 2024)]

print(f'필터링 후 행 수: {len(df_subway2):,}개')
print(f'연도 범위: {sorted(df_subway2["연도"].unique())}')

필터링 후 행 수: 26,954개
연도 범위: [np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

In [31]:
# 시간대별 컬럼 합산해서 총 승차/하차 계산
승차컬럼 = [col for col in df_subway2.columns if '승차인원' in col]
하차컬럼 = [col for col in df_subway2.columns if '하차인원' in col]

df_subway2['총_승차'] = df_subway2[승차컬럼].sum(axis=1)
df_subway2['총_하차'] = df_subway2[하차컬럼].sum(axis=1)

# 구별 + 연도별 평균 집계
df_subway_gu = df_subway2.groupby(['자치구', '연도']).agg(
    평균_승차=('총_승차', 'mean'),
    평균_하차=('총_하차', 'mean'),
).reset_index()

df_subway_gu = df_subway_gu.rename(columns={'자치구': '구명'})

print(f'행 수: {len(df_subway_gu):,}개')
print(df_subway_gu.head())

행 수: 150개
    구명    연도          평균_승차          평균_하차
0  강남구  2019  604128.458333  630089.903646
1  강남구  2020  459797.296875  479109.960938
2  강남구  2021  465546.450521  479444.174479
3  강남구  2022  514362.372396  531397.567708
4  강남구  2023  555905.528646  571618.091146

In [32]:
# 최종 ML 데이터 불러오기
df_ml_final = pd.read_csv('최종_ML용_데이터.csv', encoding='utf-8-sig')

# 구 + 연도 기준으로 합치기
df_ml_final = pd.merge(df_ml_final, df_subway_gu, on=['구명', '연도'], how='left')

print(f'행 수: {len(df_ml_final):,}개')
print(f'결측치: {df_ml_final.isnull().sum().sum()}개')
print(df_ml_final.columns.tolist())

행 수: 1,037개
결측치: 0개
['구명', '연도', '업종', '평균_당월매출', '연령대_20_매출', '연령대_30_매출', '연령대_40_매출', '연령대_50_매출', '폐업률', '평균_승차', '평균_하차']

In [33]:
df_ml_final.to_csv('최종_ML용_데이터.csv', index=False, encoding='utf-8-sig')
print('저장 완료!')

저장 완료!

In [34]:
df_work = pd.read_csv('C:/Users/human/미정프로젝트/서울시 상권분석서비스(직장인구-자치구).csv', encoding='cp949')

# 연도 추출
df_work['연도'] = df_work['기준_년분기_코드'].astype(str).str[:4].astype(int)

# 2019~2024년만 필터링
df_work = df_work[(df_work['연도'] >= 2019) & (df_work['연도'] <= 2024)]

print(f'필터링 후 행 수: {len(df_work):,}개')
print(f'연도 범위: {sorted(df_work["연도"].unique())}')

필터링 후 행 수: 600개
연도 범위: [np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

In [35]:
df_work_gu = df_work.groupby(['자치구_코드_명', '연도']).agg(
    총_직장인구=('총_직장_인구_수', 'mean'),
    직장인구_20대=('연령대_20_직장_인구_수', 'mean'),
    직장인구_30대=('연령대_30_직장_인구_수', 'mean'),
    직장인구_40대=('연령대_40_직장_인구_수', 'mean'),
    직장인구_50대=('연령대_50_직장_인구_수', 'mean'),
).reset_index()

df_work_gu = df_work_gu.rename(columns={'자치구_코드_명': '구명'})

print(f'행 수: {len(df_work_gu):,}개')
print(df_work_gu.head())

행 수: 150개
    구명    연도     총_직장인구   직장인구_20대   직장인구_30대   직장인구_40대   직장인구_50대
0  강남구  2019  937043.00  186311.00  286727.00  238932.00  155251.00
1  강남구  2020  941486.75  187173.50  288050.25  240040.25  156059.25
2  강남구  2021  956383.50  190085.00  292723.25  243863.00  158614.25
3  강남구  2022  935745.25  186188.00  286969.75  238845.50  154821.25
4  강남구  2023  897607.00  179141.25  275323.75  229296.00  148391.25

In [36]:
# 최종 ML 데이터 불러오기
df_ml_final = pd.read_csv('C:/Users/human/미정프로젝트/새 폴더/최종_ML용_데이터.csv', encoding='utf-8-sig')

# 구 + 연도 기준으로 합치기
df_ml_final = pd.merge(df_ml_final, df_work_gu, on=['구명', '연도'], how='left')

print(f'행 수: {len(df_ml_final):,}개')
print(f'결측치: {df_ml_final.isnull().sum().sum()}개')
print(f'컬럼: {df_ml_final.columns.tolist()}')

행 수: 1,037개
결측치: 0개
컬럼: ['구명', '연도', '업종', '평균_당월매출', '연령대_20_매출', '연령대_30_매출', '연령대_40_매출', '연령대_50_매출', '폐업률', '총_유동인구', '유동인구_20대', '유동인구_30대', '유동인구_40대', '유동인구_50대', '평균_승차', '평균_하차', '총_직장인구', '직장인구_20대', '직장인구_30대', '직장인구_40대', '직장인구_50대']

In [37]:
df_ml_final.to_csv('C:/Users/human/미정프로젝트/새 폴더/최종_ML용_데이터.csv', 
                   index=False, encoding='utf-8-sig')
print('저장 완료!')

저장 완료!

In [38]:
# 시간대별 유동인구 집계 (길단위인구 파일)
df_people['연도'] = df_people['기준_년분기_코드'].astype(str).str[:4].astype(int)
df_people_area2 = pd.merge(df_people, df_area_slim, on='상권_코드', how='left')

df_time = df_people_area2.groupby(['자치구_코드_명', '연도']).agg(
    출근시간_유동인구=('시간대_06_11_유동인구_수', 'mean'),
    점심시간_유동인구=('시간대_11_14_유동인구_수', 'mean'),
    저녁시간_유동인구=('시간대_17_21_유동인구_수', 'mean'),
).reset_index()

df_time = df_time[df_time['연도'] <= 2024]
df_time = df_time.rename(columns={'자치구_코드_명': '구명'})

print(f'시간대별 유동인구 행 수: {len(df_time):,}개')
print(df_time.head())

시간대별 유동인구 행 수: 150개
    구명    연도      출근시간_유동인구      점심시간_유동인구      저녁시간_유동인구
0  강남구  2019  186583.436893  149304.470874  172608.453883
1  강남구  2020  187169.245146  147216.851942  167626.730583
2  강남구  2021  179233.077670  142024.791262  160101.473301
3  강남구  2022  183077.373786  146901.286408  165668.315534
4  강남구  2023  184178.618932  149143.276699  166236.140777

In [39]:
# 연도별 추정매출 파일에서 주중/주말 비율 계산
df_sales_all['주말_비율'] = (
    df_sales_all['주말_매출_금액'] / 
    (df_sales_all['주중_매출_금액'] + df_sales_all['주말_매출_금액'])
).round(4)

# 외식 업종만 + 영역 붙이기
df_sales_ratio = df_sales_all[df_sales_all['서비스_업종_코드_명'].isin(food_list)].copy()
df_sales_ratio = pd.merge(df_sales_ratio, df_area_slim, on='상권_코드', how='left')

# 구별 + 연도별 평균
df_ratio = df_sales_ratio.groupby(['자치구_코드_명', '연도']).agg(
    주말_매출_비율=('주말_비율', 'mean')
).reset_index()

df_ratio = df_ratio[df_ratio['연도'] <= 2024]
df_ratio = df_ratio.rename(columns={'자치구_코드_명': '구명'})
df_ratio['주말_매출_비율'] = df_ratio['주말_매출_비율'].round(4)

print(f'행 수: {len(df_ratio):,}개')
print(df_ratio.head())

행 수: 150개
    구명    연도  주말_매출_비율
0  강남구  2019    0.2176
1  강남구  2020    0.2072
2  강남구  2021    0.2041
3  강남구  2022    0.2084
4  강남구  2023    0.2093

In [45]:
df_time = df_people_area2.groupby(['자치구_코드_명', '연도']).agg(
    출근시간_유동인구_06_11=('시간대_06_11_유동인구_수', 'mean'),
    점심시간_유동인구_11_14=('시간대_11_14_유동인구_수', 'mean'),
    저녁시간_유동인구_17_21=('시간대_17_21_유동인구_수', 'mean'),
).reset_index()

df_time = df_time[df_time['연도'] <= 2024]
df_time = df_time.rename(columns={'자치구_코드_명': '구명'})

print(df_time.head())

    구명    연도  출근시간_유동인구_06_11  점심시간_유동인구_11_14  저녁시간_유동인구_17_21
0  강남구  2019    186583.436893    149304.470874    172608.453883
1  강남구  2020    187169.245146    147216.851942    167626.730583
2  강남구  2021    179233.077670    142024.791262    160101.473301
3  강남구  2022    183077.373786    146901.286408    165668.315534
4  강남구  2023    184178.618932    149143.276699    166236.140777

In [43]:
# 시간대별 유동인구 합치기
df_ml_final = pd.merge(df_ml_final, df_time, on=['구명', '연도'], how='left')

# 주중/주말 비율 합치기
df_ml_final = pd.merge(df_ml_final, df_ratio, on=['구명', '연도'], how='left')

print(f'행 수: {len(df_ml_final):,}개')
print(f'결측치: {df_ml_final.isnull().sum().sum()}개')
print(f'컬럼 수: {len(df_ml_final.columns)}개')
print(f'컬럼: {df_ml_final.columns.tolist()}')

# 저장
df_ml_final.to_csv('C:/Users/human/미정프로젝트/새 폴더/최종_ML용_데이터.csv',
                   index=False, encoding='utf-8-sig')
print('\n저장 완료!')

행 수: 1,037개
결측치: 0개
컬럼 수: 33개
컬럼: ['구명', '연도', '업종', '평균_당월매출', '연령대_20_매출', '연령대_30_매출', '연령대_40_매출', '연령대_50_매출', '폐업률', '총_유동인구', '유동인구_20대', '유동인구_30대', '유동인구_40대', '유동인구_50대', '평균_승차', '평균_하차', '총_직장인구', '직장인구_20대', '직장인구_30대', '직장인구_40대', '직장인구_50대', '출근시간_유동인구', '점심시간_유동인구', '저녁시간_유동인구', '주말_매출_비율_x', '출근시간_유동인구_06_11_x', '점심시간_유동인구_11_14_x', '저녁시간_유동인구_17_21_x', '주말_매출_비율_y', '출근시간_유동인구_06_11_y', '점심시간_유동인구_11_14_y', '저녁시간_유동인구_17_21_y', '주말_매출_비율']

저장 완료!

In [47]:
df_ml_final = pd.read_csv('C:/Users/human/미정프로젝트/새 폴더/최종_ML용_데이터.csv', encoding='utf-8-sig')

# 필요한 컬럼만 선택
cols_keep = [
    '구명', '연도', '업종',
    '평균_당월매출',
    '연령대_20_매출', '연령대_30_매출', '연령대_40_매출', '연령대_50_매출',
    '폐업률',
    '총_유동인구', '유동인구_20대', '유동인구_30대', '유동인구_40대', '유동인구_50대',
    '평균_승차', '평균_하차',
    '총_직장인구', '직장인구_20대', '직장인구_30대', '직장인구_40대', '직장인구_50대',
    '출근시간_유동인구', '점심시간_유동인구', '저녁시간_유동인구',
    '주말_매출_비율'
]

df_ml_final = df_ml_final[cols_keep].copy()

# 시간 범위 포함한 이름으로 변경
df_ml_final = df_ml_final.rename(columns={
    '출근시간_유동인구': '출근시간_유동인구_06_11',
    '점심시간_유동인구': '점심시간_유동인구_11_14',
    '저녁시간_유동인구': '저녁시간_유동인구_17_21'
})

print(f'행 수: {len(df_ml_final):,}개')
print(f'컬럼 수: {len(df_ml_final.columns)}개')
print(df_ml_final.columns.tolist())

df_ml_final.to_csv('C:/Users/human/미정프로젝트/새 폴더/최종_ML용_데이터.csv',
                   index=False, encoding='utf-8-sig')
print('\n저장 완료!')

행 수: 1,037개
컬럼 수: 25개
['구명', '연도', '업종', '평균_당월매출', '연령대_20_매출', '연령대_30_매출', '연령대_40_매출', '연령대_50_매출', '폐업률', '총_유동인구', '유동인구_20대', '유동인구_30대', '유동인구_40대', '유동인구_50대', '평균_승차', '평균_하차', '총_직장인구', '직장인구_20대', '직장인구_30대', '직장인구_40대', '직장인구_50대', '출근시간_유동인구_06_11', '점심시간_유동인구_11_14', '저녁시간_유동인구_17_21', '주말_매출_비율']

저장 완료!